### ISSUE TITLE
react components render multiple times

### ISSUE THREAD

**Issue by catsonkeyboard** [hongfaqiu/nextjs13-with-antd-tailwindcss#4]
我就不用英文了,
我按照你的写法写了后,发现react组件会渲染多次,是不是有些写法有点小问题

**Comment by hongfaqiu** [comment]
我在next.config.js中开启了reactStrictMode: true, 每个组件都会渲染2次, 是不是这个原因

**Comment by catsonkeyboard** [comment]
> 

我也把reactStrictMode设置false了,我试了你的项目也是渲染多次

**Comment by catsonkeyboard** [comment]
哦,我好像找到了问题,代码中
`  if (!mounted) {
    // use your loading page
    return (
      <div className="hidden">
        {props.children}
      </div>
    );
}`
{props.children}是不是要把这个改成加载页面,我去掉就正常了,非常感谢回复

**Comment by hongfaqiu** [comment]
我设想中这里应该是在服务器端执行的代码，本意是传输可供搜索引擎抓取的页面信息，加速首屏渲染
