### ISSUE TITLE
页面白屏时间久

### ISSUE THREAD

**Issue by Bouqute** [hongfaqiu/nextjs13-with-antd-tailwindcss#5]
<img width="1014" alt="261802638-53462491-5720-41d3-81d3-04913d4fff27" src="https://github.com/hongfaqiu/nextjs13-with-antd-tailwindcss/assets/19699836/e9f40c0c-9167-4b42-9653-49466361910e">

是不是哪里有问题？ 加载这两js 这么久页面一致空白！

**Comment by Bouqute** [comment]
`https://github.com/hongfaqiu/nextjs13-with-antd-tailwindcss/assets/19699836/53462491-5720-41d3-81d3-04913d4fff27`

**Comment by hongfaqiu** [comment]
开发环境下nextjs初次启动到页面渲染出来确实挺久的
